package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * ACtasProductosId generated by hbm2java
 */
public class ACtasProductosId implements java.io.Serializable {

	private String codigoCuenta;
	private int codigoInternoDefinicion;

	public ACtasProductosId() {
	}

	public ACtasProductosId(String codigoCuenta, int codigoInternoDefinicion) {
		this.codigoCuenta = codigoCuenta;
		this.codigoInternoDefinicion = codigoInternoDefinicion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ACtasProductosId))
			return false;
		ACtasProductosId castOther = (ACtasProductosId) other;

		return ((this.getCodigoCuenta() == castOther.getCodigoCuenta()) || (this
				.getCodigoCuenta() != null
				&& castOther.getCodigoCuenta() != null && this
				.getCodigoCuenta().equals(castOther.getCodigoCuenta())))
				&& (this.getCodigoInternoDefinicion() == castOther
						.getCodigoInternoDefinicion());
	}

	public String getCodigoCuenta() {
		return this.codigoCuenta;
	}

	public int getCodigoInternoDefinicion() {
		return this.codigoInternoDefinicion;
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoCuenta() == null ? 0 : this.getCodigoCuenta()
						.hashCode());
		result = 37 * result + this.getCodigoInternoDefinicion();
		return result;
	}

	public void setCodigoCuenta(String codigoCuenta) {
		this.codigoCuenta = codigoCuenta;
	}

	public void setCodigoInternoDefinicion(int codigoInternoDefinicion) {
		this.codigoInternoDefinicion = codigoInternoDefinicion;
	}

}
