package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CFechaSistema generated by hbm2java
 */
public class CFechaSistema implements java.io.Serializable {

	private CFechaSistemaId id;

	public CFechaSistema() {
	}

	public CFechaSistema(CFechaSistemaId id) {
		this.id = id;
	}

	public CFechaSistemaId getId() {
		return this.id;
	}

	public void setId(CFechaSistemaId id) {
		this.id = id;
	}

}
