package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CFechaSistemaId generated by hbm2java
 */
public class CFechaSistemaId implements java.io.Serializable {

	private Date fechaSistema;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public CFechaSistemaId() {
	}

	public CFechaSistemaId(Date fechaSistema, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.fechaSistema = fechaSistema;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CFechaSistemaId))
			return false;
		CFechaSistemaId castOther = (CFechaSistemaId) other;

		return ((this.getFechaSistema() == castOther.getFechaSistema()) || (this
				.getFechaSistema() != null
				&& castOther.getFechaSistema() != null && this
				.getFechaSistema().equals(castOther.getFechaSistema())))
				&& ((this.getFechaInsercion() == castOther.getFechaInsercion()) || (this
						.getFechaInsercion() != null
						&& castOther.getFechaInsercion() != null && this
						.getFechaInsercion().equals(
								castOther.getFechaInsercion())))
				&& ((this.getUsuarioInsercion() == castOther
						.getUsuarioInsercion()) || (this.getUsuarioInsercion() != null
						&& castOther.getUsuarioInsercion() != null && this
						.getUsuarioInsercion().equals(
								castOther.getUsuarioInsercion())))
				&& ((this.getIpInsercion() == castOther.getIpInsercion()) || (this
						.getIpInsercion() != null
						&& castOther.getIpInsercion() != null && this
						.getIpInsercion().equals(castOther.getIpInsercion())))
				&& ((this.getFechaActualizacion() == castOther
						.getFechaActualizacion()) || (this
						.getFechaActualizacion() != null
						&& castOther.getFechaActualizacion() != null && this
						.getFechaActualizacion().equals(
								castOther.getFechaActualizacion())))
				&& ((this.getUsuarioActualizacion() == castOther
						.getUsuarioActualizacion()) || (this
						.getUsuarioActualizacion() != null
						&& castOther.getUsuarioActualizacion() != null && this
						.getUsuarioActualizacion().equals(
								castOther.getUsuarioActualizacion())))
				&& ((this.getIpActualizacion() == castOther
						.getIpActualizacion()) || (this.getIpActualizacion() != null
						&& castOther.getIpActualizacion() != null && this
						.getIpActualizacion().equals(
								castOther.getIpActualizacion())));
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public Date getFechaSistema() {
		return this.fechaSistema;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFechaSistema() == null ? 0 : this.getFechaSistema()
						.hashCode());
		result = 37
				* result
				+ (getFechaInsercion() == null ? 0 : this.getFechaInsercion()
						.hashCode());
		result = 37
				* result
				+ (getUsuarioInsercion() == null ? 0 : this
						.getUsuarioInsercion().hashCode());
		result = 37
				* result
				+ (getIpInsercion() == null ? 0 : this.getIpInsercion()
						.hashCode());
		result = 37
				* result
				+ (getFechaActualizacion() == null ? 0 : this
						.getFechaActualizacion().hashCode());
		result = 37
				* result
				+ (getUsuarioActualizacion() == null ? 0 : this
						.getUsuarioActualizacion().hashCode());
		result = 37
				* result
				+ (getIpActualizacion() == null ? 0 : this.getIpActualizacion()
						.hashCode());
		return result;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setFechaSistema(Date fechaSistema) {
		this.fechaSistema = fechaSistema;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
