package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CParentesco generated by hbm2java
 */
public class CParentesco implements java.io.Serializable {

	private int codigoInternoParentesco;
	private String descripcion;
	private Date fechaInsercion;
	private BigDecimal usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KEmpleadosClienteses = new HashSet(0);

	public CParentesco() {
	}

	public CParentesco(int codigoInternoParentesco) {
		this.codigoInternoParentesco = codigoInternoParentesco;
	}

	public CParentesco(int codigoInternoParentesco, String descripcion,
			Date fechaInsercion, BigDecimal usuarioInsercion,
			String ipInsercion, Date fechaActualizacion,
			Integer usuarioActualizacion, String ipActualizacion,
			Set KEmpleadosClienteses) {
		this.codigoInternoParentesco = codigoInternoParentesco;
		this.descripcion = descripcion;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KEmpleadosClienteses = KEmpleadosClienteses;
	}

	public int getCodigoInternoParentesco() {
		return this.codigoInternoParentesco;
	}

	public void setCodigoInternoParentesco(int codigoInternoParentesco) {
		this.codigoInternoParentesco = codigoInternoParentesco;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public BigDecimal getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(BigDecimal usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public Set getKEmpleadosClienteses() {
		return this.KEmpleadosClienteses;
	}

	public void setKEmpleadosClienteses(Set KEmpleadosClienteses) {
		this.KEmpleadosClienteses = KEmpleadosClienteses;
	}

}
