package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KAfectacionFacturas generated by hbm2java
 */
public class KAfectacionFacturas implements java.io.Serializable {

	private KAfectacionFacturasId id;
	private KConceptosFacturacion KConceptosFacturacion;
	private int numeroFactura;
	private BigDecimal vlrUnitario;
	private int cantidad;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KAfectacionFacturas() {
	}

	public KAfectacionFacturas(KAfectacionFacturasId id,
			KConceptosFacturacion KConceptosFacturacion, int numeroFactura,
			BigDecimal vlrUnitario, int cantidad) {
		this.id = id;
		this.KConceptosFacturacion = KConceptosFacturacion;
		this.numeroFactura = numeroFactura;
		this.vlrUnitario = vlrUnitario;
		this.cantidad = cantidad;
	}

	public KAfectacionFacturas(KAfectacionFacturasId id,
			KConceptosFacturacion KConceptosFacturacion, int numeroFactura,
			BigDecimal vlrUnitario, int cantidad, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KConceptosFacturacion = KConceptosFacturacion;
		this.numeroFactura = numeroFactura;
		this.vlrUnitario = vlrUnitario;
		this.cantidad = cantidad;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public KAfectacionFacturasId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KConceptosFacturacion getKConceptosFacturacion() {
		return this.KConceptosFacturacion;
	}

	public int getNumeroFactura() {
		return this.numeroFactura;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public BigDecimal getVlrUnitario() {
		return this.vlrUnitario;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setId(KAfectacionFacturasId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKConceptosFacturacion(
			KConceptosFacturacion KConceptosFacturacion) {
		this.KConceptosFacturacion = KConceptosFacturacion;
	}

	public void setNumeroFactura(int numeroFactura) {
		this.numeroFactura = numeroFactura;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public void setVlrUnitario(BigDecimal vlrUnitario) {
		this.vlrUnitario = vlrUnitario;
	}

}
