package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KAfectacionFacturasId generated by hbm2java
 */
public class KAfectacionFacturasId implements java.io.Serializable {

	private int numeroPedido;
	private int codIntConcepto;

	public KAfectacionFacturasId() {
	}

	public KAfectacionFacturasId(int numeroPedido, int codIntConcepto) {
		this.numeroPedido = numeroPedido;
		this.codIntConcepto = codIntConcepto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KAfectacionFacturasId))
			return false;
		KAfectacionFacturasId castOther = (KAfectacionFacturasId) other;

		return (this.getNumeroPedido() == castOther.getNumeroPedido())
				&& (this.getCodIntConcepto() == castOther.getCodIntConcepto());
	}

	public int getCodIntConcepto() {
		return this.codIntConcepto;
	}

	public int getNumeroPedido() {
		return this.numeroPedido;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumeroPedido();
		result = 37 * result + this.getCodIntConcepto();
		return result;
	}

	public void setCodIntConcepto(int codIntConcepto) {
		this.codIntConcepto = codIntConcepto;
	}

	public void setNumeroPedido(int numeroPedido) {
		this.numeroPedido = numeroPedido;
	}

}
