package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KBancosTerceros generated by hbm2java
 */
public class KBancosTerceros implements java.io.Serializable {

	private int codIntBkoTer;
	private CTipoIdentificacion CTipoIdentificacion;
	private String razonSocial;
	private String nombreContacto;
	private String nroIdentificacion;
	private String telefono;
	private String direccionIp;
	private String url;
	private String usuarioConexion;
	private String clave;
	private String tipoInterface;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KDefinicionProductoses = new HashSet(0);
	private Set KDefinicionInterfaceses = new HashSet(0);

	public KBancosTerceros() {
	}

	public KBancosTerceros(int codIntBkoTer,
			CTipoIdentificacion CTipoIdentificacion, String razonSocial,
			String nombreContacto, String nroIdentificacion, String telefono) {
		this.codIntBkoTer = codIntBkoTer;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.razonSocial = razonSocial;
		this.nombreContacto = nombreContacto;
		this.nroIdentificacion = nroIdentificacion;
		this.telefono = telefono;
	}

	public KBancosTerceros(int codIntBkoTer,
			CTipoIdentificacion CTipoIdentificacion, String razonSocial,
			String nombreContacto, String nroIdentificacion, String telefono,
			String direccionIp, String url, String usuarioConexion,
			String clave, String tipoInterface, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KDefinicionProductoses,
			Set KDefinicionInterfaceses) {
		this.codIntBkoTer = codIntBkoTer;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.razonSocial = razonSocial;
		this.nombreContacto = nombreContacto;
		this.nroIdentificacion = nroIdentificacion;
		this.telefono = telefono;
		this.direccionIp = direccionIp;
		this.url = url;
		this.usuarioConexion = usuarioConexion;
		this.clave = clave;
		this.tipoInterface = tipoInterface;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KDefinicionProductoses = KDefinicionProductoses;
		this.KDefinicionInterfaceses = KDefinicionInterfaceses;
	}

	public int getCodIntBkoTer() {
		return this.codIntBkoTer;
	}

	public void setCodIntBkoTer(int codIntBkoTer) {
		this.codIntBkoTer = codIntBkoTer;
	}

	public CTipoIdentificacion getCTipoIdentificacion() {
		return this.CTipoIdentificacion;
	}

	public void setCTipoIdentificacion(CTipoIdentificacion CTipoIdentificacion) {
		this.CTipoIdentificacion = CTipoIdentificacion;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public String getNroIdentificacion() {
		return this.nroIdentificacion;
	}

	public void setNroIdentificacion(String nroIdentificacion) {
		this.nroIdentificacion = nroIdentificacion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccionIp() {
		return this.direccionIp;
	}

	public void setDireccionIp(String direccionIp) {
		this.direccionIp = direccionIp;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getUsuarioConexion() {
		return this.usuarioConexion;
	}

	public void setUsuarioConexion(String usuarioConexion) {
		this.usuarioConexion = usuarioConexion;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getTipoInterface() {
		return this.tipoInterface;
	}

	public void setTipoInterface(String tipoInterface) {
		this.tipoInterface = tipoInterface;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public Set getKDefinicionProductoses() {
		return this.KDefinicionProductoses;
	}

	public void setKDefinicionProductoses(Set KDefinicionProductoses) {
		this.KDefinicionProductoses = KDefinicionProductoses;
	}

	public Set getKDefinicionInterfaceses() {
		return this.KDefinicionInterfaceses;
	}

	public void setKDefinicionInterfaceses(Set KDefinicionInterfaceses) {
		this.KDefinicionInterfaceses = KDefinicionInterfaceses;
	}

}
