package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KColumnasInterfaces generated by hbm2java
 */
public class KColumnasInterfaces implements java.io.Serializable {

	private KColumnasInterfacesId id;
	private KDefinicionInterfaces KDefinicionInterfaces;
	private Date fechaInsercion;
	private BigDecimal usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KColumnasInterfaces() {
	}

	public KColumnasInterfaces(KColumnasInterfacesId id,
			KDefinicionInterfaces KDefinicionInterfaces) {
		this.id = id;
		this.KDefinicionInterfaces = KDefinicionInterfaces;
	}

	public KColumnasInterfaces(KColumnasInterfacesId id,
			KDefinicionInterfaces KDefinicionInterfaces, Date fechaInsercion,
			BigDecimal usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KDefinicionInterfaces = KDefinicionInterfaces;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public KColumnasInterfacesId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KDefinicionInterfaces getKDefinicionInterfaces() {
		return this.KDefinicionInterfaces;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public BigDecimal getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setId(KColumnasInterfacesId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKDefinicionInterfaces(
			KDefinicionInterfaces KDefinicionInterfaces) {
		this.KDefinicionInterfaces = KDefinicionInterfaces;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(BigDecimal usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
