package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KColumnasInterfacesId generated by hbm2java
 */
public class KColumnasInterfacesId implements java.io.Serializable {

	private int codigoInternoInterface;
	private int codIntBancoTero;
	private String nombreTabla;
	private String nombreColumna;

	public KColumnasInterfacesId() {
	}

	public KColumnasInterfacesId(int codigoInternoInterface,
			int codIntBancoTero, String nombreTabla, String nombreColumna) {
		this.codigoInternoInterface = codigoInternoInterface;
		this.codIntBancoTero = codIntBancoTero;
		this.nombreTabla = nombreTabla;
		this.nombreColumna = nombreColumna;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KColumnasInterfacesId))
			return false;
		KColumnasInterfacesId castOther = (KColumnasInterfacesId) other;

		return (this.getCodigoInternoInterface() == castOther
				.getCodigoInternoInterface())
				&& (this.getCodIntBancoTero() == castOther.getCodIntBancoTero())
				&& ((this.getNombreTabla() == castOther.getNombreTabla()) || (this
						.getNombreTabla() != null
						&& castOther.getNombreTabla() != null && this
						.getNombreTabla().equals(castOther.getNombreTabla())))
				&& ((this.getNombreColumna() == castOther.getNombreColumna()) || (this
						.getNombreColumna() != null
						&& castOther.getNombreColumna() != null && this
						.getNombreColumna()
						.equals(castOther.getNombreColumna())));
	}

	public int getCodigoInternoInterface() {
		return this.codigoInternoInterface;
	}

	public int getCodIntBancoTero() {
		return this.codIntBancoTero;
	}

	public String getNombreColumna() {
		return this.nombreColumna;
	}

	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoInterface();
		result = 37 * result + this.getCodIntBancoTero();
		result = 37
				* result
				+ (getNombreTabla() == null ? 0 : this.getNombreTabla()
						.hashCode());
		result = 37
				* result
				+ (getNombreColumna() == null ? 0 : this.getNombreColumna()
						.hashCode());
		return result;
	}

	public void setCodigoInternoInterface(int codigoInternoInterface) {
		this.codigoInternoInterface = codigoInternoInterface;
	}

	public void setCodIntBancoTero(int codIntBancoTero) {
		this.codIntBancoTero = codIntBancoTero;
	}

	public void setNombreColumna(String nombreColumna) {
		this.nombreColumna = nombreColumna;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

}
