package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KCorreo generated by hbm2java
 */
public class KCorreo implements java.io.Serializable {

	private String numeroGuia;
	private KEmpresaCorreo KEmpresaCorreo;
	private int codigoInternoUsuario;
	private int codigoInternoEmpresa;
	private Date fechaEnvio;
	private String entregado;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KCorreo() {
	}

	public KCorreo(String numeroGuia, KEmpresaCorreo KEmpresaCorreo,
			int codigoInternoUsuario, int codigoInternoEmpresa,
			Date fechaEnvio, String entregado) {
		this.numeroGuia = numeroGuia;
		this.KEmpresaCorreo = KEmpresaCorreo;
		this.codigoInternoUsuario = codigoInternoUsuario;
		this.codigoInternoEmpresa = codigoInternoEmpresa;
		this.fechaEnvio = fechaEnvio;
		this.entregado = entregado;
	}

	public KCorreo(String numeroGuia, KEmpresaCorreo KEmpresaCorreo,
			int codigoInternoUsuario, int codigoInternoEmpresa,
			Date fechaEnvio, String entregado, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.numeroGuia = numeroGuia;
		this.KEmpresaCorreo = KEmpresaCorreo;
		this.codigoInternoUsuario = codigoInternoUsuario;
		this.codigoInternoEmpresa = codigoInternoEmpresa;
		this.fechaEnvio = fechaEnvio;
		this.entregado = entregado;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public int getCodigoInternoEmpresa() {
		return this.codigoInternoEmpresa;
	}

	public int getCodigoInternoUsuario() {
		return this.codigoInternoUsuario;
	}

	public String getEntregado() {
		return this.entregado;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaEnvio() {
		return this.fechaEnvio;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KEmpresaCorreo getKEmpresaCorreo() {
		return this.KEmpresaCorreo;
	}

	public String getNumeroGuia() {
		return this.numeroGuia;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setCodigoInternoEmpresa(int codigoInternoEmpresa) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
	}

	public void setCodigoInternoUsuario(int codigoInternoUsuario) {
		this.codigoInternoUsuario = codigoInternoUsuario;
	}

	public void setEntregado(String entregado) {
		this.entregado = entregado;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKEmpresaCorreo(KEmpresaCorreo KEmpresaCorreo) {
		this.KEmpresaCorreo = KEmpresaCorreo;
	}

	public void setNumeroGuia(String numeroGuia) {
		this.numeroGuia = numeroGuia;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
