package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KDefinicionInterfacesId generated by hbm2java
 */
public class KDefinicionInterfacesId implements java.io.Serializable {

	private int codigoInternoInterface;
	private int codigoInternoBanco3ro;

	public KDefinicionInterfacesId() {
	}

	public KDefinicionInterfacesId(int codigoInternoInterface,
			int codigoInternoBanco3ro) {
		this.codigoInternoInterface = codigoInternoInterface;
		this.codigoInternoBanco3ro = codigoInternoBanco3ro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KDefinicionInterfacesId))
			return false;
		KDefinicionInterfacesId castOther = (KDefinicionInterfacesId) other;

		return (this.getCodigoInternoInterface() == castOther
				.getCodigoInternoInterface())
				&& (this.getCodigoInternoBanco3ro() == castOther
						.getCodigoInternoBanco3ro());
	}

	public int getCodigoInternoBanco3ro() {
		return this.codigoInternoBanco3ro;
	}

	public int getCodigoInternoInterface() {
		return this.codigoInternoInterface;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoInterface();
		result = 37 * result + this.getCodigoInternoBanco3ro();
		return result;
	}

	public void setCodigoInternoBanco3ro(int codigoInternoBanco3ro) {
		this.codigoInternoBanco3ro = codigoInternoBanco3ro;
	}

	public void setCodigoInternoInterface(int codigoInternoInterface) {
		this.codigoInternoInterface = codigoInternoInterface;
	}

}
