package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KDefinicionDeducciones generated by hbm2java
 */
public class KDefinicionDeducciones implements java.io.Serializable {

	private int codigoInternoDeduccion;
	private String descripcion;
	private String abreviado;
	private String formaLiquidar;
	private BigDecimal valor;
	private String concepto;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private BigDecimal usuarioActualizacion;
	private String ipActualizacion;
	private Set KProductosDeduccioneses = new HashSet(0);
	private Set KFacturacionDeduccioneses = new HashSet(0);

	public KDefinicionDeducciones() {
	}

	public KDefinicionDeducciones(int codigoInternoDeduccion,
			String descripcion, String abreviado, String formaLiquidar,
			BigDecimal valor, String concepto) {
		this.codigoInternoDeduccion = codigoInternoDeduccion;
		this.descripcion = descripcion;
		this.abreviado = abreviado;
		this.formaLiquidar = formaLiquidar;
		this.valor = valor;
		this.concepto = concepto;
	}

	public KDefinicionDeducciones(int codigoInternoDeduccion,
			String descripcion, String abreviado, String formaLiquidar,
			BigDecimal valor, String concepto, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, BigDecimal usuarioActualizacion,
			String ipActualizacion, Set KProductosDeduccioneses,
			Set KFacturacionDeduccioneses) {
		this.codigoInternoDeduccion = codigoInternoDeduccion;
		this.descripcion = descripcion;
		this.abreviado = abreviado;
		this.formaLiquidar = formaLiquidar;
		this.valor = valor;
		this.concepto = concepto;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KProductosDeduccioneses = KProductosDeduccioneses;
		this.KFacturacionDeduccioneses = KFacturacionDeduccioneses;
	}

	public int getCodigoInternoDeduccion() {
		return this.codigoInternoDeduccion;
	}

	public void setCodigoInternoDeduccion(int codigoInternoDeduccion) {
		this.codigoInternoDeduccion = codigoInternoDeduccion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	public String getFormaLiquidar() {
		return this.formaLiquidar;
	}

	public void setFormaLiquidar(String formaLiquidar) {
		this.formaLiquidar = formaLiquidar;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public BigDecimal getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(BigDecimal usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public Set getKProductosDeduccioneses() {
		return this.KProductosDeduccioneses;
	}

	public void setKProductosDeduccioneses(Set KProductosDeduccioneses) {
		this.KProductosDeduccioneses = KProductosDeduccioneses;
	}

	public Set getKFacturacionDeduccioneses() {
		return this.KFacturacionDeduccioneses;
	}

	public void setKFacturacionDeduccioneses(Set KFacturacionDeduccioneses) {
		this.KFacturacionDeduccioneses = KFacturacionDeduccioneses;
	}

}
