package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KDefinicionInterfaces generated by hbm2java
 */
public class KDefinicionInterfaces implements java.io.Serializable {

	private KDefinicionInterfacesId id;
	private KBancosTerceros KBancosTerceros;
	private String descripcion;
	private String caracterSeparacion;
	private String caracterSaltoPagina;
	private String caracterSaltoLinea;
	private String anchoFijoVariable;
	private String caracterRellenoAlfa;
	private String caracterRellenoNumber;
	private String rellenoAlfaDeIz;
	private String rellenoNumDeIz;
	private String titulos;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KColumnasInterfaceses = new HashSet(0);

	public KDefinicionInterfaces() {
	}

	public KDefinicionInterfaces(KDefinicionInterfacesId id,
			KBancosTerceros KBancosTerceros, String descripcion,
			String caracterSeparacion, String caracterSaltoPagina,
			String caracterSaltoLinea, String anchoFijoVariable, String titulos) {
		this.id = id;
		this.KBancosTerceros = KBancosTerceros;
		this.descripcion = descripcion;
		this.caracterSeparacion = caracterSeparacion;
		this.caracterSaltoPagina = caracterSaltoPagina;
		this.caracterSaltoLinea = caracterSaltoLinea;
		this.anchoFijoVariable = anchoFijoVariable;
		this.titulos = titulos;
	}

	public KDefinicionInterfaces(KDefinicionInterfacesId id,
			KBancosTerceros KBancosTerceros, String descripcion,
			String caracterSeparacion, String caracterSaltoPagina,
			String caracterSaltoLinea, String anchoFijoVariable,
			String caracterRellenoAlfa, String caracterRellenoNumber,
			String rellenoAlfaDeIz, String rellenoNumDeIz, String titulos,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KColumnasInterfaceses) {
		this.id = id;
		this.KBancosTerceros = KBancosTerceros;
		this.descripcion = descripcion;
		this.caracterSeparacion = caracterSeparacion;
		this.caracterSaltoPagina = caracterSaltoPagina;
		this.caracterSaltoLinea = caracterSaltoLinea;
		this.anchoFijoVariable = anchoFijoVariable;
		this.caracterRellenoAlfa = caracterRellenoAlfa;
		this.caracterRellenoNumber = caracterRellenoNumber;
		this.rellenoAlfaDeIz = rellenoAlfaDeIz;
		this.rellenoNumDeIz = rellenoNumDeIz;
		this.titulos = titulos;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KColumnasInterfaceses = KColumnasInterfaceses;
	}

	public String getAnchoFijoVariable() {
		return this.anchoFijoVariable;
	}

	public String getCaracterRellenoAlfa() {
		return this.caracterRellenoAlfa;
	}

	public String getCaracterRellenoNumber() {
		return this.caracterRellenoNumber;
	}

	public String getCaracterSaltoLinea() {
		return this.caracterSaltoLinea;
	}

	public String getCaracterSaltoPagina() {
		return this.caracterSaltoPagina;
	}

	public String getCaracterSeparacion() {
		return this.caracterSeparacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public KDefinicionInterfacesId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KBancosTerceros getKBancosTerceros() {
		return this.KBancosTerceros;
	}

	public Set getKColumnasInterfaceses() {
		return this.KColumnasInterfaceses;
	}

	public String getRellenoAlfaDeIz() {
		return this.rellenoAlfaDeIz;
	}

	public String getRellenoNumDeIz() {
		return this.rellenoNumDeIz;
	}

	public String getTitulos() {
		return this.titulos;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setAnchoFijoVariable(String anchoFijoVariable) {
		this.anchoFijoVariable = anchoFijoVariable;
	}

	public void setCaracterRellenoAlfa(String caracterRellenoAlfa) {
		this.caracterRellenoAlfa = caracterRellenoAlfa;
	}

	public void setCaracterRellenoNumber(String caracterRellenoNumber) {
		this.caracterRellenoNumber = caracterRellenoNumber;
	}

	public void setCaracterSaltoLinea(String caracterSaltoLinea) {
		this.caracterSaltoLinea = caracterSaltoLinea;
	}

	public void setCaracterSaltoPagina(String caracterSaltoPagina) {
		this.caracterSaltoPagina = caracterSaltoPagina;
	}

	public void setCaracterSeparacion(String caracterSeparacion) {
		this.caracterSeparacion = caracterSeparacion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setId(KDefinicionInterfacesId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKBancosTerceros(KBancosTerceros KBancosTerceros) {
		this.KBancosTerceros = KBancosTerceros;
	}

	public void setKColumnasInterfaceses(Set KColumnasInterfaceses) {
		this.KColumnasInterfaceses = KColumnasInterfaceses;
	}

	public void setRellenoAlfaDeIz(String rellenoAlfaDeIz) {
		this.rellenoAlfaDeIz = rellenoAlfaDeIz;
	}

	public void setRellenoNumDeIz(String rellenoNumDeIz) {
		this.rellenoNumDeIz = rellenoNumDeIz;
	}

	public void setTitulos(String titulos) {
		this.titulos = titulos;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
