package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KDefinicionProductos generated by hbm2java
 */
public class KDefinicionProductos implements java.io.Serializable {

	private int codigoInternoDefinicion;
	private KBancosTerceros KBancosTerceros;
	private KEmpresas KEmpresas;
	private KProductos KProductos;
	private String descripcionProducto;
	private BigDecimal porcAdministracion;
	private String abreviado;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KPivotCoorPros = new HashSet(0);
	private Set KMvtoBeneficiadoses = new HashSet(0);
	private Set KProductosDeduccioneses = new HashSet(0);
	private Set KFacturases = new HashSet(0);

	public KDefinicionProductos() {
	}

	public KDefinicionProductos(int codigoInternoDefinicion,
			KBancosTerceros KBancosTerceros, KEmpresas KEmpresas,
			KProductos KProductos, String descripcionProducto,
			BigDecimal porcAdministracion, String abreviado) {
		this.codigoInternoDefinicion = codigoInternoDefinicion;
		this.KBancosTerceros = KBancosTerceros;
		this.KEmpresas = KEmpresas;
		this.KProductos = KProductos;
		this.descripcionProducto = descripcionProducto;
		this.porcAdministracion = porcAdministracion;
		this.abreviado = abreviado;
	}

	public KDefinicionProductos(int codigoInternoDefinicion,
			KBancosTerceros KBancosTerceros, KEmpresas KEmpresas,
			KProductos KProductos, String descripcionProducto,
			BigDecimal porcAdministracion, String abreviado,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KPivotCoorPros,
			Set KMvtoBeneficiadoses, Set KProductosDeduccioneses,
			Set KFacturases) {
		this.codigoInternoDefinicion = codigoInternoDefinicion;
		this.KBancosTerceros = KBancosTerceros;
		this.KEmpresas = KEmpresas;
		this.KProductos = KProductos;
		this.descripcionProducto = descripcionProducto;
		this.porcAdministracion = porcAdministracion;
		this.abreviado = abreviado;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KPivotCoorPros = KPivotCoorPros;
		this.KMvtoBeneficiadoses = KMvtoBeneficiadoses;
		this.KProductosDeduccioneses = KProductosDeduccioneses;
		this.KFacturases = KFacturases;
	}

	public String getAbreviado() {
		return this.abreviado;
	}

	public int getCodigoInternoDefinicion() {
		return this.codigoInternoDefinicion;
	}

	public String getDescripcionProducto() {
		return this.descripcionProducto;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KBancosTerceros getKBancosTerceros() {
		return this.KBancosTerceros;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public Set getKFacturases() {
		return this.KFacturases;
	}

	public Set getKMvtoBeneficiadoses() {
		return this.KMvtoBeneficiadoses;
	}

	public Set getKPivotCoorPros() {
		return this.KPivotCoorPros;
	}

	public KProductos getKProductos() {
		return this.KProductos;
	}

	public Set getKProductosDeduccioneses() {
		return this.KProductosDeduccioneses;
	}

	public BigDecimal getPorcAdministracion() {
		return this.porcAdministracion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setAbreviado(String abreviado) {
		this.abreviado = abreviado;
	}

	public void setCodigoInternoDefinicion(int codigoInternoDefinicion) {
		this.codigoInternoDefinicion = codigoInternoDefinicion;
	}

	public void setDescripcionProducto(String descripcionProducto) {
		this.descripcionProducto = descripcionProducto;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKBancosTerceros(KBancosTerceros KBancosTerceros) {
		this.KBancosTerceros = KBancosTerceros;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public void setKFacturases(Set KFacturases) {
		this.KFacturases = KFacturases;
	}

	public void setKMvtoBeneficiadoses(Set KMvtoBeneficiadoses) {
		this.KMvtoBeneficiadoses = KMvtoBeneficiadoses;
	}

	public void setKPivotCoorPros(Set KPivotCoorPros) {
		this.KPivotCoorPros = KPivotCoorPros;
	}

	public void setKProductos(KProductos KProductos) {
		this.KProductos = KProductos;
	}

	public void setKProductosDeduccioneses(Set KProductosDeduccioneses) {
		this.KProductosDeduccioneses = KProductosDeduccioneses;
	}

	public void setPorcAdministracion(BigDecimal porcAdministracion) {
		this.porcAdministracion = porcAdministracion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
