package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KDirecciones generated by hbm2java
 */
public class KDirecciones implements java.io.Serializable {

	private KDireccionesId id;
	private CTipoUbicacion CTipoUbicacion;
	private CCiudad CCiudad;
	private KEmpleadosClientes KEmpleadosClientes;
	private String descripcion;
	private int tipoDireccion;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private BigDecimal usuarioActualizacion;
	private String ipActualizacion;

	public KDirecciones() {
	}

	public KDirecciones(KDireccionesId id, CTipoUbicacion CTipoUbicacion,
			CCiudad CCiudad, KEmpleadosClientes KEmpleadosClientes,
			String descripcion, int tipoDireccion) {
		this.id = id;
		this.CTipoUbicacion = CTipoUbicacion;
		this.CCiudad = CCiudad;
		this.KEmpleadosClientes = KEmpleadosClientes;
		this.descripcion = descripcion;
		this.tipoDireccion = tipoDireccion;
	}

	public KDirecciones(KDireccionesId id, CTipoUbicacion CTipoUbicacion,
			CCiudad CCiudad, KEmpleadosClientes KEmpleadosClientes,
			String descripcion, int tipoDireccion, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, BigDecimal usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.CTipoUbicacion = CTipoUbicacion;
		this.CCiudad = CCiudad;
		this.KEmpleadosClientes = KEmpleadosClientes;
		this.descripcion = descripcion;
		this.tipoDireccion = tipoDireccion;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public KDireccionesId getId() {
		return this.id;
	}

	public void setId(KDireccionesId id) {
		this.id = id;
	}

	public CTipoUbicacion getCTipoUbicacion() {
		return this.CTipoUbicacion;
	}

	public void setCTipoUbicacion(CTipoUbicacion CTipoUbicacion) {
		this.CTipoUbicacion = CTipoUbicacion;
	}

	public CCiudad getCCiudad() {
		return this.CCiudad;
	}

	public void setCCiudad(CCiudad CCiudad) {
		this.CCiudad = CCiudad;
	}

	public KEmpleadosClientes getKEmpleadosClientes() {
		return this.KEmpleadosClientes;
	}

	public void setKEmpleadosClientes(KEmpleadosClientes KEmpleadosClientes) {
		this.KEmpleadosClientes = KEmpleadosClientes;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getTipoDireccion() {
		return this.tipoDireccion;
	}

	public void setTipoDireccion(int tipoDireccion) {
		this.tipoDireccion = tipoDireccion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public BigDecimal getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(BigDecimal usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

}
