package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KEmpleadosClientes generated by hbm2java
 */
public class KEmpleadosClientes implements java.io.Serializable {

	private int codigoInternoEmpleado;
	private KEmpleadosClientes KEmpleadosClientes;
	private CTipoIdentificacion CTipoIdentificacion;
	private CParentesco CParentesco;
	private String nroIdentificacion;
	private String nombre;
	private int cargo;
	private String dummy;
	private String estado;
	private String correoElectronico;
	private Integer direccionExtracto;
	private Integer direccionPersonal;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KDireccioneses = new HashSet(0);
	private Set KMvtoBeneficiadoses = new HashSet(0);
	private Set KEmpleadosClienteses = new HashSet(0);

	public KEmpleadosClientes() {
	}

	public KEmpleadosClientes(int codigoInternoEmpleado,
			CTipoIdentificacion CTipoIdentificacion, String nroIdentificacion,
			String nombre, int cargo, String dummy, String estado) {
		this.codigoInternoEmpleado = codigoInternoEmpleado;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.nroIdentificacion = nroIdentificacion;
		this.nombre = nombre;
		this.cargo = cargo;
		this.dummy = dummy;
		this.estado = estado;
	}

	public KEmpleadosClientes(int codigoInternoEmpleado,
			KEmpleadosClientes KEmpleadosClientes,
			CTipoIdentificacion CTipoIdentificacion, CParentesco CParentesco,
			String nroIdentificacion, String nombre, int cargo, String dummy,
			String estado, String correoElectronico, Integer direccionExtracto,
			Integer direccionPersonal, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KDireccioneses,
			Set KMvtoBeneficiadoses, Set KEmpleadosClienteses) {
		this.codigoInternoEmpleado = codigoInternoEmpleado;
		this.KEmpleadosClientes = KEmpleadosClientes;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.CParentesco = CParentesco;
		this.nroIdentificacion = nroIdentificacion;
		this.nombre = nombre;
		this.cargo = cargo;
		this.dummy = dummy;
		this.estado = estado;
		this.correoElectronico = correoElectronico;
		this.direccionExtracto = direccionExtracto;
		this.direccionPersonal = direccionPersonal;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KDireccioneses = KDireccioneses;
		this.KMvtoBeneficiadoses = KMvtoBeneficiadoses;
		this.KEmpleadosClienteses = KEmpleadosClienteses;
	}

	public int getCodigoInternoEmpleado() {
		return this.codigoInternoEmpleado;
	}

	public void setCodigoInternoEmpleado(int codigoInternoEmpleado) {
		this.codigoInternoEmpleado = codigoInternoEmpleado;
	}

	public KEmpleadosClientes getKEmpleadosClientes() {
		return this.KEmpleadosClientes;
	}

	public void setKEmpleadosClientes(KEmpleadosClientes KEmpleadosClientes) {
		this.KEmpleadosClientes = KEmpleadosClientes;
	}

	public CTipoIdentificacion getCTipoIdentificacion() {
		return this.CTipoIdentificacion;
	}

	public void setCTipoIdentificacion(CTipoIdentificacion CTipoIdentificacion) {
		this.CTipoIdentificacion = CTipoIdentificacion;
	}

	public CParentesco getCParentesco() {
		return this.CParentesco;
	}

	public void setCParentesco(CParentesco CParentesco) {
		this.CParentesco = CParentesco;
	}

	public String getNroIdentificacion() {
		return this.nroIdentificacion;
	}

	public void setNroIdentificacion(String nroIdentificacion) {
		this.nroIdentificacion = nroIdentificacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCargo() {
		return this.cargo;
	}

	public void setCargo(int cargo) {
		this.cargo = cargo;
	}

	public String getDummy() {
		return this.dummy;
	}

	public void setDummy(String dummy) {
		this.dummy = dummy;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public Integer getDireccionExtracto() {
		return this.direccionExtracto;
	}

	public void setDireccionExtracto(Integer direccionExtracto) {
		this.direccionExtracto = direccionExtracto;
	}

	public Integer getDireccionPersonal() {
		return this.direccionPersonal;
	}

	public void setDireccionPersonal(Integer direccionPersonal) {
		this.direccionPersonal = direccionPersonal;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public Set getKDireccioneses() {
		return this.KDireccioneses;
	}

	public void setKDireccioneses(Set KDireccioneses) {
		this.KDireccioneses = KDireccioneses;
	}

	public Set getKMvtoBeneficiadoses() {
		return this.KMvtoBeneficiadoses;
	}

	public void setKMvtoBeneficiadoses(Set KMvtoBeneficiadoses) {
		this.KMvtoBeneficiadoses = KMvtoBeneficiadoses;
	}

	public Set getKEmpleadosClienteses() {
		return this.KEmpleadosClienteses;
	}

	public void setKEmpleadosClienteses(Set KEmpleadosClienteses) {
		this.KEmpleadosClienteses = KEmpleadosClienteses;
	}

}
