package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KEmpresaCorreo generated by hbm2java
 */
public class KEmpresaCorreo implements java.io.Serializable {

	private int codEmpresaCorreo;
	private String razonSocial;
	private String telefono;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KCorreos = new HashSet(0);

	public KEmpresaCorreo() {
	}

	public KEmpresaCorreo(int codEmpresaCorreo, String razonSocial,
			String telefono) {
		this.codEmpresaCorreo = codEmpresaCorreo;
		this.razonSocial = razonSocial;
		this.telefono = telefono;
	}

	public KEmpresaCorreo(int codEmpresaCorreo, String razonSocial,
			String telefono, Date fechaInsercion, Integer usuarioInsercion,
			String ipInsercion, Date fechaActualizacion,
			Integer usuarioActualizacion, String ipActualizacion, Set KCorreos) {
		this.codEmpresaCorreo = codEmpresaCorreo;
		this.razonSocial = razonSocial;
		this.telefono = telefono;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KCorreos = KCorreos;
	}

	public int getCodEmpresaCorreo() {
		return this.codEmpresaCorreo;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public Set getKCorreos() {
		return this.KCorreos;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setCodEmpresaCorreo(int codEmpresaCorreo) {
		this.codEmpresaCorreo = codEmpresaCorreo;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKCorreos(Set KCorreos) {
		this.KCorreos = KCorreos;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
