package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KFacturacionDeduccionesId generated by hbm2java
 */
public class KFacturacionDeduccionesId implements java.io.Serializable {

	private int codigoInternoDeduccion;
	private int codIntConcepto;

	public KFacturacionDeduccionesId() {
	}

	public KFacturacionDeduccionesId(int codigoInternoDeduccion,
			int codIntConcepto) {
		this.codigoInternoDeduccion = codigoInternoDeduccion;
		this.codIntConcepto = codIntConcepto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KFacturacionDeduccionesId))
			return false;
		KFacturacionDeduccionesId castOther = (KFacturacionDeduccionesId) other;

		return (this.getCodigoInternoDeduccion() == castOther
				.getCodigoInternoDeduccion())
				&& (this.getCodIntConcepto() == castOther.getCodIntConcepto());
	}

	public int getCodigoInternoDeduccion() {
		return this.codigoInternoDeduccion;
	}

	public int getCodIntConcepto() {
		return this.codIntConcepto;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoDeduccion();
		result = 37 * result + this.getCodIntConcepto();
		return result;
	}

	public void setCodigoInternoDeduccion(int codigoInternoDeduccion) {
		this.codigoInternoDeduccion = codigoInternoDeduccion;
	}

	public void setCodIntConcepto(int codIntConcepto) {
		this.codIntConcepto = codIntConcepto;
	}

}
