package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KFacturas generated by hbm2java
 */
public class KFacturas implements java.io.Serializable {

	private KFacturasId id;
	private KEmpresas KEmpresas;
	private KDefinicionProductos KDefinicionProductos;
	private Date fechaPago;
	private Date fechaFacturacion;
	private Date fechaDispersion;
	private int cantidad;
	private BigDecimal vlrUnitario;
	private Date fechaItem;
	private Integer facturaNumero;
	private String dispersado;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KFacturas() {
	}

	public KFacturas(KFacturasId id, KEmpresas KEmpresas,
			KDefinicionProductos KDefinicionProductos, Date fechaPago,
			Date fechaFacturacion, Date fechaDispersion, int cantidad,
			BigDecimal vlrUnitario, Date fechaItem, Integer facturaNumero,
			String dispersado, Date fechaInsercion, Integer usuarioInsercion,
			String ipInsercion, Date fechaActualizacion,
			Integer usuarioActualizacion, String ipActualizacion) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KDefinicionProductos = KDefinicionProductos;
		this.fechaPago = fechaPago;
		this.fechaFacturacion = fechaFacturacion;
		this.fechaDispersion = fechaDispersion;
		this.cantidad = cantidad;
		this.vlrUnitario = vlrUnitario;
		this.fechaItem = fechaItem;
		this.facturaNumero = facturaNumero;
		this.dispersado = dispersado;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public KFacturas(KFacturasId id, KEmpresas KEmpresas,
			KDefinicionProductos KDefinicionProductos, int cantidad) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KDefinicionProductos = KDefinicionProductos;
		this.cantidad = cantidad;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public String getDispersado() {
		return this.dispersado;
	}

	public Integer getFacturaNumero() {
		return this.facturaNumero;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaDispersion() {
		return this.fechaDispersion;
	}

	public Date getFechaFacturacion() {
		return this.fechaFacturacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public Date getFechaItem() {
		return this.fechaItem;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public KFacturasId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KDefinicionProductos getKDefinicionProductos() {
		return this.KDefinicionProductos;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public BigDecimal getVlrUnitario() {
		return this.vlrUnitario;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public void setDispersado(String dispersado) {
		this.dispersado = dispersado;
	}

	public void setFacturaNumero(Integer facturaNumero) {
		this.facturaNumero = facturaNumero;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaDispersion(Date fechaDispersion) {
		this.fechaDispersion = fechaDispersion;
	}

	public void setFechaFacturacion(Date fechaFacturacion) {
		this.fechaFacturacion = fechaFacturacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setFechaItem(Date fechaItem) {
		this.fechaItem = fechaItem;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public void setId(KFacturasId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKDefinicionProductos(
			KDefinicionProductos KDefinicionProductos) {
		this.KDefinicionProductos = KDefinicionProductos;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public void setVlrUnitario(BigDecimal vlrUnitario) {
		this.vlrUnitario = vlrUnitario;
	}

}
