package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KMovimientoSaldoClientes generated by hbm2java
 */
public class KMovimientoSaldoClientes implements java.io.Serializable {

	private KMovimientoSaldoClientesId id;
	private KEmpresas KEmpresas;
	private Date fechaAbono;
	private BigDecimal valorAbono;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KMovimientoSaldoClientes() {
	}

	public KMovimientoSaldoClientes(KMovimientoSaldoClientesId id,
			KEmpresas KEmpresas, Date fechaAbono, BigDecimal valorAbono) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.fechaAbono = fechaAbono;
		this.valorAbono = valorAbono;
	}

	public KMovimientoSaldoClientes(KMovimientoSaldoClientesId id,
			KEmpresas KEmpresas, Date fechaAbono, BigDecimal valorAbono,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.fechaAbono = fechaAbono;
		this.valorAbono = valorAbono;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public KMovimientoSaldoClientesId getId() {
		return this.id;
	}

	public void setId(KMovimientoSaldoClientesId id) {
		this.id = id;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public Date getFechaAbono() {
		return this.fechaAbono;
	}

	public void setFechaAbono(Date fechaAbono) {
		this.fechaAbono = fechaAbono;
	}

	public BigDecimal getValorAbono() {
		return this.valorAbono;
	}

	public void setValorAbono(BigDecimal valorAbono) {
		this.valorAbono = valorAbono;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

}
