package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KMvtoBeneficiados generated by hbm2java
 */
public class KMvtoBeneficiados implements java.io.Serializable {

	private KMvtoBeneficiadosId id;
	private KEmpresas KEmpresas;
	private KEmpleadosClientes KEmpleadosClientes;
	private KDefinicionProductos KDefinicionProductos;
	private CTipoIdentificacion CTipoIdentificacion;
	private String nroIdentificacionEmpleado;
	private Date fechaDispersion;
	private BigDecimal valorTransaccion;
	private String naturaleza;
	private String abreviadoTransaccion;
	private int pedido;
	private Integer factura;
	private String procesado;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KMvtoBeneficiados() {
	}

	public KMvtoBeneficiados(KMvtoBeneficiadosId id, KEmpresas KEmpresas,
			KEmpleadosClientes KEmpleadosClientes,
			KDefinicionProductos KDefinicionProductos,
			CTipoIdentificacion CTipoIdentificacion,
			String nroIdentificacionEmpleado, BigDecimal valorTransaccion,
			String naturaleza, String abreviadoTransaccion, int pedido) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KEmpleadosClientes = KEmpleadosClientes;
		this.KDefinicionProductos = KDefinicionProductos;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.nroIdentificacionEmpleado = nroIdentificacionEmpleado;
		this.valorTransaccion = valorTransaccion;
		this.naturaleza = naturaleza;
		this.abreviadoTransaccion = abreviadoTransaccion;
		this.pedido = pedido;
	}

	public KMvtoBeneficiados(KMvtoBeneficiadosId id, KEmpresas KEmpresas,
			KEmpleadosClientes KEmpleadosClientes,
			KDefinicionProductos KDefinicionProductos,
			CTipoIdentificacion CTipoIdentificacion,
			String nroIdentificacionEmpleado, Date fechaDispersion,
			BigDecimal valorTransaccion, String naturaleza,
			String abreviadoTransaccion, int pedido, Integer factura,
			String procesado, Date fechaInsercion, Integer usuarioInsercion,
			String ipInsercion, Date fechaActualizacion,
			Integer usuarioActualizacion, String ipActualizacion) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KEmpleadosClientes = KEmpleadosClientes;
		this.KDefinicionProductos = KDefinicionProductos;
		this.CTipoIdentificacion = CTipoIdentificacion;
		this.nroIdentificacionEmpleado = nroIdentificacionEmpleado;
		this.fechaDispersion = fechaDispersion;
		this.valorTransaccion = valorTransaccion;
		this.naturaleza = naturaleza;
		this.abreviadoTransaccion = abreviadoTransaccion;
		this.pedido = pedido;
		this.factura = factura;
		this.procesado = procesado;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public KMvtoBeneficiadosId getId() {
		return this.id;
	}

	public void setId(KMvtoBeneficiadosId id) {
		this.id = id;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public KEmpleadosClientes getKEmpleadosClientes() {
		return this.KEmpleadosClientes;
	}

	public void setKEmpleadosClientes(KEmpleadosClientes KEmpleadosClientes) {
		this.KEmpleadosClientes = KEmpleadosClientes;
	}

	public KDefinicionProductos getKDefinicionProductos() {
		return this.KDefinicionProductos;
	}

	public void setKDefinicionProductos(
			KDefinicionProductos KDefinicionProductos) {
		this.KDefinicionProductos = KDefinicionProductos;
	}

	public CTipoIdentificacion getCTipoIdentificacion() {
		return this.CTipoIdentificacion;
	}

	public void setCTipoIdentificacion(CTipoIdentificacion CTipoIdentificacion) {
		this.CTipoIdentificacion = CTipoIdentificacion;
	}

	public String getNroIdentificacionEmpleado() {
		return this.nroIdentificacionEmpleado;
	}

	public void setNroIdentificacionEmpleado(String nroIdentificacionEmpleado) {
		this.nroIdentificacionEmpleado = nroIdentificacionEmpleado;
	}

	public Date getFechaDispersion() {
		return this.fechaDispersion;
	}

	public void setFechaDispersion(Date fechaDispersion) {
		this.fechaDispersion = fechaDispersion;
	}

	public BigDecimal getValorTransaccion() {
		return this.valorTransaccion;
	}

	public void setValorTransaccion(BigDecimal valorTransaccion) {
		this.valorTransaccion = valorTransaccion;
	}

	public String getNaturaleza() {
		return this.naturaleza;
	}

	public void setNaturaleza(String naturaleza) {
		this.naturaleza = naturaleza;
	}

	public String getAbreviadoTransaccion() {
		return this.abreviadoTransaccion;
	}

	public void setAbreviadoTransaccion(String abreviadoTransaccion) {
		this.abreviadoTransaccion = abreviadoTransaccion;
	}

	public int getPedido() {
		return this.pedido;
	}

	public void setPedido(int pedido) {
		this.pedido = pedido;
	}

	public Integer getFactura() {
		return this.factura;
	}

	public void setFactura(Integer factura) {
		this.factura = factura;
	}

	public String getProcesado() {
		return this.procesado;
	}

	public void setProcesado(String procesado) {
		this.procesado = procesado;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

}
