package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KPivotCoorPro generated by hbm2java
 */
public class KPivotCoorPro implements java.io.Serializable {

	private KPivotCoorProId id;
	private KEmpresas KEmpresas;
	private KUsuariosEmpresas KUsuariosEmpresas;
	private KDefinicionProductos KDefinicionProductos;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private BigDecimal usuarioActualizacion;
	private String ipActualizacion;

	public KPivotCoorPro() {
	}

	public KPivotCoorPro(KPivotCoorProId id, KEmpresas KEmpresas,
			KUsuariosEmpresas KUsuariosEmpresas,
			KDefinicionProductos KDefinicionProductos) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KUsuariosEmpresas = KUsuariosEmpresas;
		this.KDefinicionProductos = KDefinicionProductos;
	}

	public KPivotCoorPro(KPivotCoorProId id, KEmpresas KEmpresas,
			KUsuariosEmpresas KUsuariosEmpresas,
			KDefinicionProductos KDefinicionProductos, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, BigDecimal usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KUsuariosEmpresas = KUsuariosEmpresas;
		this.KDefinicionProductos = KDefinicionProductos;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public KPivotCoorProId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KDefinicionProductos getKDefinicionProductos() {
		return this.KDefinicionProductos;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public KUsuariosEmpresas getKUsuariosEmpresas() {
		return this.KUsuariosEmpresas;
	}

	public BigDecimal getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setId(KPivotCoorProId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKDefinicionProductos(
			KDefinicionProductos KDefinicionProductos) {
		this.KDefinicionProductos = KDefinicionProductos;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public void setKUsuariosEmpresas(KUsuariosEmpresas KUsuariosEmpresas) {
		this.KUsuariosEmpresas = KUsuariosEmpresas;
	}

	public void setUsuarioActualizacion(BigDecimal usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
