package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KPivotGteCuentaEmpresasId generated by hbm2java
 */
public class KPivotGteCuentaEmpresasId implements java.io.Serializable {

	private int codigoInternoEmpresa;
	private int codigoInternoFuncionario;

	public KPivotGteCuentaEmpresasId() {
	}

	public KPivotGteCuentaEmpresasId(int codigoInternoEmpresa,
			int codigoInternoFuncionario) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
		this.codigoInternoFuncionario = codigoInternoFuncionario;
	}

	public int getCodigoInternoEmpresa() {
		return this.codigoInternoEmpresa;
	}

	public void setCodigoInternoEmpresa(int codigoInternoEmpresa) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
	}

	public int getCodigoInternoFuncionario() {
		return this.codigoInternoFuncionario;
	}

	public void setCodigoInternoFuncionario(int codigoInternoFuncionario) {
		this.codigoInternoFuncionario = codigoInternoFuncionario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KPivotGteCuentaEmpresasId))
			return false;
		KPivotGteCuentaEmpresasId castOther = (KPivotGteCuentaEmpresasId) other;

		return (this.getCodigoInternoEmpresa() == castOther
				.getCodigoInternoEmpresa())
				&& (this.getCodigoInternoFuncionario() == castOther
						.getCodigoInternoFuncionario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoEmpresa();
		result = 37 * result + this.getCodigoInternoFuncionario();
		return result;
	}

}
