package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KPivotGteCuentaEmpresas generated by hbm2java
 */
public class KPivotGteCuentaEmpresas implements java.io.Serializable {

	private KPivotGteCuentaEmpresasId id;
	private KEmpresas KEmpresas;
	private KUsuariosEmpresas KUsuariosEmpresas;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private BigDecimal usuarioActualizacion;
	private String ipActualizacion;

	public KPivotGteCuentaEmpresas() {
	}

	public KPivotGteCuentaEmpresas(KPivotGteCuentaEmpresasId id,
			KEmpresas KEmpresas, KUsuariosEmpresas KUsuariosEmpresas) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KUsuariosEmpresas = KUsuariosEmpresas;
	}

	public KPivotGteCuentaEmpresas(KPivotGteCuentaEmpresasId id,
			KEmpresas KEmpresas, KUsuariosEmpresas KUsuariosEmpresas,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, BigDecimal usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KEmpresas = KEmpresas;
		this.KUsuariosEmpresas = KUsuariosEmpresas;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public KPivotGteCuentaEmpresasId getId() {
		return this.id;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public KUsuariosEmpresas getKUsuariosEmpresas() {
		return this.KUsuariosEmpresas;
	}

	public BigDecimal getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setId(KPivotGteCuentaEmpresasId id) {
		this.id = id;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public void setKUsuariosEmpresas(KUsuariosEmpresas KUsuariosEmpresas) {
		this.KUsuariosEmpresas = KUsuariosEmpresas;
	}

	public void setUsuarioActualizacion(BigDecimal usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
