package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * KProductosDeducciones generated by hbm2java
 */
public class KProductosDeducciones implements java.io.Serializable {

	private KProductosDeduccionesId id;
	private KDefinicionProductos KDefinicionProductos;
	private KDefinicionDeducciones KDefinicionDeducciones;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KProductosDeducciones() {
	}

	public KProductosDeducciones(KProductosDeduccionesId id,
			KDefinicionProductos KDefinicionProductos,
			KDefinicionDeducciones KDefinicionDeducciones) {
		this.id = id;
		this.KDefinicionProductos = KDefinicionProductos;
		this.KDefinicionDeducciones = KDefinicionDeducciones;
	}

	public KProductosDeducciones(KProductosDeduccionesId id,
			KDefinicionProductos KDefinicionProductos,
			KDefinicionDeducciones KDefinicionDeducciones, Date fechaInsercion,
			Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.id = id;
		this.KDefinicionProductos = KDefinicionProductos;
		this.KDefinicionDeducciones = KDefinicionDeducciones;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public KProductosDeduccionesId getId() {
		return this.id;
	}

	public void setId(KProductosDeduccionesId id) {
		this.id = id;
	}

	public KDefinicionProductos getKDefinicionProductos() {
		return this.KDefinicionProductos;
	}

	public void setKDefinicionProductos(
			KDefinicionProductos KDefinicionProductos) {
		this.KDefinicionProductos = KDefinicionProductos;
	}

	public KDefinicionDeducciones getKDefinicionDeducciones() {
		return this.KDefinicionDeducciones;
	}

	public void setKDefinicionDeducciones(
			KDefinicionDeducciones KDefinicionDeducciones) {
		this.KDefinicionDeducciones = KDefinicionDeducciones;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

}
