package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KRecursosXRolesId generated by hbm2java
 */
public class KRecursosXRolesId implements java.io.Serializable {

	private int codigoInternoRole;
	private int codigoInternoRecurso;

	public KRecursosXRolesId() {
	}

	public KRecursosXRolesId(int codigoInternoRole, int codigoInternoRecurso) {
		this.codigoInternoRole = codigoInternoRole;
		this.codigoInternoRecurso = codigoInternoRecurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KRecursosXRolesId))
			return false;
		KRecursosXRolesId castOther = (KRecursosXRolesId) other;

		return (this.getCodigoInternoRole() == castOther.getCodigoInternoRole())
				&& (this.getCodigoInternoRecurso() == castOther
						.getCodigoInternoRecurso());
	}

	public int getCodigoInternoRecurso() {
		return this.codigoInternoRecurso;
	}

	public int getCodigoInternoRole() {
		return this.codigoInternoRole;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoRole();
		result = 37 * result + this.getCodigoInternoRecurso();
		return result;
	}

	public void setCodigoInternoRecurso(int codigoInternoRecurso) {
		this.codigoInternoRecurso = codigoInternoRecurso;
	}

	public void setCodigoInternoRole(int codigoInternoRole) {
		this.codigoInternoRole = codigoInternoRole;
	}

}
