package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * KRolesEmpresasId generated by hbm2java
 */
public class KRolesEmpresasId implements java.io.Serializable {

	private int codigoInternoEmpresa;
	private int codigoInternoUsuario;
	private int codigoInternoRole;

	public KRolesEmpresasId() {
	}

	public KRolesEmpresasId(int codigoInternoEmpresa, int codigoInternoUsuario,
			int codigoInternoRole) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
		this.codigoInternoUsuario = codigoInternoUsuario;
		this.codigoInternoRole = codigoInternoRole;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KRolesEmpresasId))
			return false;
		KRolesEmpresasId castOther = (KRolesEmpresasId) other;

		return (this.getCodigoInternoEmpresa() == castOther
				.getCodigoInternoEmpresa())
				&& (this.getCodigoInternoUsuario() == castOther
						.getCodigoInternoUsuario())
				&& (this.getCodigoInternoRole() == castOther
						.getCodigoInternoRole());
	}

	public int getCodigoInternoEmpresa() {
		return this.codigoInternoEmpresa;
	}

	public int getCodigoInternoRole() {
		return this.codigoInternoRole;
	}

	public int getCodigoInternoUsuario() {
		return this.codigoInternoUsuario;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoInternoEmpresa();
		result = 37 * result + this.getCodigoInternoUsuario();
		result = 37 * result + this.getCodigoInternoRole();
		return result;
	}

	public void setCodigoInternoEmpresa(int codigoInternoEmpresa) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
	}

	public void setCodigoInternoRole(int codigoInternoRole) {
		this.codigoInternoRole = codigoInternoRole;
	}

	public void setCodigoInternoUsuario(int codigoInternoUsuario) {
		this.codigoInternoUsuario = codigoInternoUsuario;
	}

}
