package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KRoles generated by hbm2java
 */
public class KRoles implements java.io.Serializable {

	private int codigoInternoRole;
	private String descripcion;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KRecursosXRoleses = new HashSet(0);
	private Set KRolesEmpresases = new HashSet(0);

	public KRoles() {
	}

	public KRoles(int codigoInternoRole, String descripcion) {
		this.codigoInternoRole = codigoInternoRole;
		this.descripcion = descripcion;
	}

	public KRoles(int codigoInternoRole, String descripcion,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KRecursosXRoleses, Set KRolesEmpresases) {
		this.codigoInternoRole = codigoInternoRole;
		this.descripcion = descripcion;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KRecursosXRoleses = KRecursosXRoleses;
		this.KRolesEmpresases = KRolesEmpresases;
	}

	public int getCodigoInternoRole() {
		return this.codigoInternoRole;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public Set getKRecursosXRoleses() {
		return this.KRecursosXRoleses;
	}

	public Set getKRolesEmpresases() {
		return this.KRolesEmpresases;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setCodigoInternoRole(int codigoInternoRole) {
		this.codigoInternoRole = codigoInternoRole;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKRecursosXRoleses(Set KRecursosXRoleses) {
		this.KRecursosXRoleses = KRecursosXRoleses;
	}

	public void setKRolesEmpresases(Set KRolesEmpresases) {
		this.KRolesEmpresases = KRolesEmpresases;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
