package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KSaldosXEmpresas generated by hbm2java
 */
public class KSaldosXEmpresas implements java.io.Serializable {

	private int codigoInternoEmpresa;
	private KEmpresas KEmpresas;
	private String estadoSaldo;
	private BigDecimal saldoAnterior;
	private BigDecimal saldoActual;
	private Date fechaSobregiroActual;
	private Date fechaUltimoSobregiro;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KSaldosXEmpresas() {
	}

	public KSaldosXEmpresas(KEmpresas KEmpresas, String estadoSaldo) {
		this.KEmpresas = KEmpresas;
		this.estadoSaldo = estadoSaldo;
	}

	public KSaldosXEmpresas(KEmpresas KEmpresas, String estadoSaldo,
			BigDecimal saldoAnterior, BigDecimal saldoActual,
			Date fechaSobregiroActual, Date fechaUltimoSobregiro,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.KEmpresas = KEmpresas;
		this.estadoSaldo = estadoSaldo;
		this.saldoAnterior = saldoAnterior;
		this.saldoActual = saldoActual;
		this.fechaSobregiroActual = fechaSobregiroActual;
		this.fechaUltimoSobregiro = fechaUltimoSobregiro;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public int getCodigoInternoEmpresa() {
		return this.codigoInternoEmpresa;
	}

	public void setCodigoInternoEmpresa(int codigoInternoEmpresa) {
		this.codigoInternoEmpresa = codigoInternoEmpresa;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public String getEstadoSaldo() {
		return this.estadoSaldo;
	}

	public void setEstadoSaldo(String estadoSaldo) {
		this.estadoSaldo = estadoSaldo;
	}

	public BigDecimal getSaldoAnterior() {
		return this.saldoAnterior;
	}

	public void setSaldoAnterior(BigDecimal saldoAnterior) {
		this.saldoAnterior = saldoAnterior;
	}

	public BigDecimal getSaldoActual() {
		return this.saldoActual;
	}

	public void setSaldoActual(BigDecimal saldoActual) {
		this.saldoActual = saldoActual;
	}

	public Date getFechaSobregiroActual() {
		return this.fechaSobregiroActual;
	}

	public void setFechaSobregiroActual(Date fechaSobregiroActual) {
		this.fechaSobregiroActual = fechaSobregiroActual;
	}

	public Date getFechaUltimoSobregiro() {
		return this.fechaUltimoSobregiro;
	}

	public void setFechaUltimoSobregiro(Date fechaUltimoSobregiro) {
		this.fechaUltimoSobregiro = fechaUltimoSobregiro;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

}
