package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KUsuariosEmpresas generated by hbm2java
 */
public class KUsuariosEmpresas implements java.io.Serializable {

	private int codigoInternoUsuario;
	private KEmpresas KEmpresas;
	private CTipoCargo CTipoCargo;
	private String nombreFuncionario;
	private String correoElectronico;
	private String dependencia;
	private String direccion;
	private Date fechaInsercion;
	private Integer usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;
	private Set KPivotGteCuentaEmpresases = new HashSet(0);
	private Set KPivotCoorPros = new HashSet(0);
	private KUsuariosFunciones KUsuariosFunciones;
	private Set KRolesEmpresases = new HashSet(0);

	public KUsuariosEmpresas() {
	}

	public KUsuariosEmpresas(int codigoInternoUsuario, KEmpresas KEmpresas,
			CTipoCargo tipoCargo, String nombreFuncionario,
			String correoElectronico, String dependencia, String direccion) {
		this.codigoInternoUsuario = codigoInternoUsuario;
		this.KEmpresas = KEmpresas;
		this.CTipoCargo = tipoCargo;
		this.nombreFuncionario = nombreFuncionario;
		this.correoElectronico = correoElectronico;
		this.dependencia = dependencia;
		this.direccion = direccion;
	}

	public KUsuariosEmpresas(int codigoInternoUsuario, KEmpresas KEmpresas,
			CTipoCargo tipoCargo, String nombreFuncionario,
			String correoElectronico, String dependencia, String direccion,
			Date fechaInsercion, Integer usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion, Set KPivotGteCuentaEmpresases,
			Set KPivotCoorPros, KUsuariosFunciones KUsuariosFunciones,
			Set KRolesEmpresases) {
		this.codigoInternoUsuario = codigoInternoUsuario;
		this.KEmpresas = KEmpresas;
		this.CTipoCargo = tipoCargo;
		this.nombreFuncionario = nombreFuncionario;
		this.correoElectronico = correoElectronico;
		this.dependencia = dependencia;
		this.direccion = direccion;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
		this.KPivotGteCuentaEmpresases = KPivotGteCuentaEmpresases;
		this.KPivotCoorPros = KPivotCoorPros;
		this.KUsuariosFunciones = KUsuariosFunciones;
		this.KRolesEmpresases = KRolesEmpresases;
	}

	public int getCodigoInternoUsuario() {
		return this.codigoInternoUsuario;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public CTipoCargo getCTipoCargo() {
		return this.CTipoCargo;
	}

	public String getDependencia() {
		return this.dependencia;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public KEmpresas getKEmpresas() {
		return this.KEmpresas;
	}

	public Set getKPivotCoorPros() {
		return this.KPivotCoorPros;
	}

	public Set getKPivotGteCuentaEmpresases() {
		return this.KPivotGteCuentaEmpresases;
	}

	public Set getKRolesEmpresases() {
		return this.KRolesEmpresases;
	}

	public KUsuariosFunciones getKUsuariosFunciones() {
		return this.KUsuariosFunciones;
	}

	public String getNombreFuncionario() {
		return this.nombreFuncionario;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public Integer getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public void setCodigoInternoUsuario(int codigoInternoUsuario) {
		this.codigoInternoUsuario = codigoInternoUsuario;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public void setCTipoCargo(CTipoCargo CTipoCargo) {
		this.CTipoCargo = CTipoCargo;
	}

	public void setDependencia(String dependencia) {
		this.dependencia = dependencia;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setKEmpresas(KEmpresas KEmpresas) {
		this.KEmpresas = KEmpresas;
	}

	public void setKPivotCoorPros(Set KPivotCoorPros) {
		this.KPivotCoorPros = KPivotCoorPros;
	}

	public void setKPivotGteCuentaEmpresases(Set KPivotGteCuentaEmpresases) {
		this.KPivotGteCuentaEmpresases = KPivotGteCuentaEmpresases;
	}

	public void setKRolesEmpresases(Set KRolesEmpresases) {
		this.KRolesEmpresases = KRolesEmpresases;
	}

	public void setKUsuariosFunciones(KUsuariosFunciones KUsuariosFunciones) {
		this.KUsuariosFunciones = KUsuariosFunciones;
	}

	public void setNombreFuncionario(String nombreFuncionario) {
		this.nombreFuncionario = nombreFuncionario;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(Integer usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

}
