package com.pp.admin.hibernate;

// Generated Jul 25, 2011 11:41:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KUsuariosFunciones generated by hbm2java
 */
public class KUsuariosFunciones implements java.io.Serializable {

	private int codigoInternoUsuario;
	private KUsuariosEmpresas usuariosEmpresas;
	private String autorizaPago;
	private String informarPedido;
	private String informarFactura;
	private String informarSobregiro;
	private String enviarPlasticos;
	private String coordinador;
	private Date fechaInsercion;
	private BigDecimal usuarioInsercion;
	private String ipInsercion;
	private Date fechaActualizacion;
	private Integer usuarioActualizacion;
	private String ipActualizacion;

	public KUsuariosFunciones() {
	}

	public KUsuariosFunciones(KUsuariosEmpresas usuariosEmpresas,
			String autorizaPago, String informarPedido, String informarFactura,
			String informarSobregiro, String enviarPlasticos, String coordinador) {
		this.usuariosEmpresas = usuariosEmpresas;
		this.autorizaPago = autorizaPago;
		this.informarPedido = informarPedido;
		this.informarFactura = informarFactura;
		this.informarSobregiro = informarSobregiro;
		this.enviarPlasticos = enviarPlasticos;
		this.coordinador = coordinador;
	}

	public KUsuariosFunciones(KUsuariosEmpresas usuariosEmpresas,
			String autorizaPago, String informarPedido, String informarFactura,
			String informarSobregiro, String enviarPlasticos,
			String coordinador, Date fechaInsercion,
			BigDecimal usuarioInsercion, String ipInsercion,
			Date fechaActualizacion, Integer usuarioActualizacion,
			String ipActualizacion) {
		this.usuariosEmpresas = usuariosEmpresas;
		this.autorizaPago = autorizaPago;
		this.informarPedido = informarPedido;
		this.informarFactura = informarFactura;
		this.informarSobregiro = informarSobregiro;
		this.enviarPlasticos = enviarPlasticos;
		this.coordinador = coordinador;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ipActualizacion = ipActualizacion;
	}

	public String getAutorizaPago() {
		return this.autorizaPago;
	}

	public int getCodigoInternoUsuario() {
		return this.codigoInternoUsuario;
	}

	
	public String getCoordinador() {
		return this.coordinador;
	}

	public String getEnviarPlasticos() {
		return this.enviarPlasticos;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	public String getInformarFactura() {
		return this.informarFactura;
	}

	public String getInformarPedido() {
		return this.informarPedido;
	}

	public String getInformarSobregiro() {
		return this.informarSobregiro;
	}

	public String getIpActualizacion() {
		return this.ipActualizacion;
	}

	public String getIpInsercion() {
		return this.ipInsercion;
	}

	public Integer getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public BigDecimal getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	public KUsuariosEmpresas getUsuariosEmpresas() {
		return usuariosEmpresas;
	}

	public void setAutorizaPago(String autorizaPago) {
		this.autorizaPago = autorizaPago;
	}

	public void setCodigoInternoUsuario(int codigoInternoUsuario) {
		this.codigoInternoUsuario = codigoInternoUsuario;
	}

	public void setCoordinador(String coordinador) {
		this.coordinador = coordinador;
	}

	public void setEnviarPlasticos(String enviarPlasticos) {
		this.enviarPlasticos = enviarPlasticos;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	public void setInformarFactura(String informarFactura) {
		this.informarFactura = informarFactura;
	}

	public void setInformarPedido(String informarPedido) {
		this.informarPedido = informarPedido;
	}

	public void setInformarSobregiro(String informarSobregiro) {
		this.informarSobregiro = informarSobregiro;
	}

	public void setIpActualizacion(String ipActualizacion) {
		this.ipActualizacion = ipActualizacion;
	}

	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	public void setUsuarioActualizacion(Integer usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public void setUsuarioInsercion(BigDecimal usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	public void setUsuariosEmpresas(KUsuariosEmpresas usuariosEmpresas) {
		this.usuariosEmpresas = usuariosEmpresas;
	}
	
	

}
